<img src="image/openw3/default/assistant/wizard_left_{{widget.statusStep1}}.png" class="{{widget.className}}_left"></img>
<div class="{{widget.className}}_{{widget.statusStep1}} {{widget.className}}_step1">
	<div id="{{widget.id}}_subpart1" class="{{widget.className}}_subpart">
		<div class="{{widget.className}}_subpart_{{widget.statusPart1}} {{widget.className}}_subpart1"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart2}} {{widget.className}}_subpart2"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart3}} {{widget.className}}_subpart3"></div>
	</div>
</div>
<img src="image/openw3/default/assistant/wizard_right_active_next.png" class="{{widget.className}}_right"></img>
<span {{widget.i18nStep1|dataI18n}} class="{{widget.className}}_step1Title"></span>
