<select id="{{widget.id}}_selectPlug1">
	<!--<option name="{{widget.id}}_s1">Automatisch</option>-->
</select>
<select id="{{widget.id}}_selectPlug2">
	<!--<option name="{{widget.id}}_s1">Automatisch</option>-->
</select>

<div id="" class="{{widget.className}}_template">
	<option id="{{widget.id}}_templateAuto" name="{{widget.id}}" {{widget.i18nAuto|dataI18n}}></option>
	<option id="{{widget.id}}_templateRow" name="{{widget.id}}"></option>
</div>
