{% autoescape off%}
<div {{widget.i18nTitle|dataI18n}}>{{widget.title|optional}}</div>
<span id="{{widget.id}}_value">
{% for item in widget.content %}
	{% if item.href %}<a target="_blank" href="{{item.href}}">{% endif %}
	{% if item.i18nHelp %}
		<span id="{{widget.id}}_item{{forloop.counter}}"
			data-action="show"
			data-target="{{forloop.counter}}"
			class="{{widget.className}}_help"
		>
	{% endif %}
	{% if item.target %}
		<span id="{{widget.id}}_item{{forloop.counter}}"
			data-action="navigate"
			data-menu="{{item.target.0}}"
			data-view="{{item.target.1}}"
			class="{{widget.className}}_nav"
		>
	{% endif %}
	{% for subItem in item.i18n|zipLongest:item.value %}
		<span {{subItem.0|dataI18n}}>{{subItem.1|optional}}</span>
	{% endfor %}
	{% if item.target %}</span>{% endif %}
	{% if item.i18nHelp %}</span>{% endif %}
	{% if item.href %}</a>{% endif %}
	{% if item.br %}<br>{% endif %}
{% endfor %}
</span>
<div>
{% for item in widget.content %}
{% if item.i18nHelp %}
	<div id="{{widget.id}}_hidden{{forloop.counter}}"
		class="{{widget.className}}_hide" 
		data-target="{{forloop.counter}}"
	>
		<span {{item.i18nHelp|dataI18n}}></span>
		<span>
			<span {{widget.i18nClose|dataI18n}} data-action="hide">
				{{widget.close|optional}}	
			</span>
		</span>
	</div>
{% endif %}
{% endfor %}
</div>
{% endautoescape %}
