<div id="{{widget.id}}_error" {{widget.i18nError|dataI18n}}></div>
<input type="password" id="{{widget.id}}_Value">
<input type="text" id="{{widget.id}}_altValue">
<label for="{{widget.id}}_Value" {{widget.i18n|dataI18n}}>{{widget.value|optional}}</label>

{% if widget.displayOption %}
	<br style="clear:right;" />

	<input type="checkbox" id="{{widget.id}}_checkboxValue" data-action="show">
	<label for="{{widget.id}}_checkboxValue" {{widget.i18nCheckbox|dataI18n}}>{{widget.checkbox|optional}}</label>
{% endif %}

