<img src="image/openw3/default/assistant/wizard_left_{{widget.statusStep1}}.png" class="{{widget.className}}_left"></img>
<div class="{{widget.className}}_{{widget.statusStep1}} {{widget.className}}_step1">
	<div id="{{widget.id}}_subpart1" class="{{widget.className}}_subpart">
		<div class="{{widget.className}}_subpart_{{widget.statusPart11}} {{widget.className}}_subpart1"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart12}} {{widget.className}}_subpart2"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart13}} {{widget.className}}_subpart3"></div>
	</div>
</div>
<img src="image/openw3/default/assistant/wizard_connect_{{widget.statusStep1}}_{{widget.statusStep2}}.png" class="{{widget.className}}_step12"></img>
<div class="{{widget.className}}_{{widget.statusStep2}} {{widget.className}}_step2">
	<div id="{{widget.id}}_subpart2" class="{{widget.className}}_subpart">
		<div class="{{widget.className}}_subpart_{{widget.statusPart21}} {{widget.className}}_subpart1"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart22}} {{widget.className}}_subpart2"></div>
		<div class="{{widget.className}}_subpart_{{widget.statusPart23}} {{widget.className}}_subpart3"></div>
	</div>
</div>
<img src="image/openw3/default/assistant/wizard_right_{{widget.statusStep2}}.png" class="{{widget.className}}_right"></img>
<span {{widget.i18nStep1|dataI18n}} class="{{widget.className}}_step1Title"></span>
<span {{widget.i18nStep2|dataI18n}} class="{{widget.className}}_step2Title"></span>
