<div id="{{widget.id}}_error" {{widget.i18nError|dataI18n}}></div>
<div>
	<input type="text" id="{{widget.id}}_value0" maxlength="1" value="0">
	<input type="text" id="{{widget.id}}_value1" maxlength="1" value="0">
	<input type="text" id="{{widget.id}}_value2" maxlength="1" value="0">
	<input type="text" id="{{widget.id}}_value3" maxlength="1" value="1">
</div>

<label for="{{widget.id}}_value0" {{widget.i18n|dataI18n}}>{{widget.label|optional}}</label>

