<table border="0" cellspacing="0" cellpadding="0">
	<thead>
		<tr>
			<td></td>
			<td colspan="2">
				<p {{widget.i18n|dataI18n}}></p>
				<p {{widget.i18nHide|dataI18n}}></p>
			</td>
		</tr>
	</thead>
	<tbody id="{{widget.id}}_table"></tbody>
</table>

<div id="" class="{{widget.className}}_template">
	<table>
		<tr id="{{widget.id}}_templateRow"><td></td><td><input type="checkbox" /></td><td></td></tr>
	</table>
</div>

